baseURL = "https://projectodevida.org/"
languageCode = "en-us"
title = "Projecto de Vida"
theme = "hugo-book"

ignoreLogs = ['warning-goldmark-raw-html']

defaultContentLanguageInSubdir = true
BookSection = 'docs'
publishDir = "docs"

[permalinks]
  docs = "/:slug/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  customCSS = ["css/custom.scss"]
  favicon = "favicon.ico"

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/en/"
    weight = 1

  [[languages.en.menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/en/blog/"
    weight = 2

  [[languages.en.menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/en/projects/"
    weight = 3
    children = [
      {name = "Publications", url = "/en/projects/publications/"},
      {name = "Events", url = "/en/projects/events/"}
    ]

  [[languages.en.menu.main]]
    name = "Resources"
    url = "/en/resources/"
    weight = 4

  [[languages.en.menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/en/contact/"
    weight = 5


[languages.pt.menu]
  [[languages.pt.menu.main]]
    identifier = "home"
    name = "Início"
    url = "/pt/"
    weight = 1

  [[languages.pt.menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/pt/blog/"
    weight = 2

  [[languages.pt.menu.main]]
    identifier = "projects"
    name = "Projetos"
    url = "/pt/projects/"
    weight = 3
    children = [
      {name = "Publicações", url = "/pt/projects/publications/"},
      {name = "Eventos", url = "/pt/projects/events/"}
    ]

  [[languages.pt.menu.main]]
    name = "Recursos"
    url = "/pt/resources/"
    weight = 4

  [[languages.pt.menu.main]]
    identifier = "contact"
    name = "Contato"
    url = "/pt/contact/"
    weight = 5
    
    
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true


[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Projecto de Vida'
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
    [languages.en.taxonomies] 
      category = "categories"
      tag = "tags"
  

  [languages.pt]
    contentDir = 'content/pt'
    disabled = false
    languageCode = 'pt-PT'
    languageDirection = 'ltr'
    languageName = 'Português'
    title = 'Projecto de Vida'
    weight = 2
    [languages.pt.params]
      subtitle = 'Referências, Tutoriais e Explicações'
    [languages.pt.taxonomies]
      category = "categorias"
      tag = "tags"


