baseURL = "http://example.org/"
languageCode = "en-us"
title = "Projecto de Vida"
theme = "hugo-book"

defaultContentLanguageInSubdir = true
BookSection = 'docs'

[params]
  customCSS = ["css/custom.scss"]
  favicon = "favicon.ico"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 3
  children = [
    {name = "Publications", url = "/projects/publications/"},
    {name = "Events", url = "/projects/events/"}
  ]

  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5
    
    
    
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true


[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Projecto de Vida'
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
    [languages.en.taxonomies] 
      category = "categories"
      tag = "tags"
  

  [languages.pt]
    contentDir = 'content/pt'
    disabled = false
    languageCode = 'pt-PT'
    languageDirection = 'ltr'
    languageName = 'Português'
    title = 'Projecto de Vida'
    weight = 2
    [languages.pt.params]
      subtitle = 'Referências, Tutoriais e Explicações'
    [languages.pt.taxonomies]
      category = "categorias"
      tag = "tags"
